#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# feh --bg-fill ~/pics/wallpapers/simon2.jpg --bg-fill ~/pics/wallpapers/simon3.jpg --bg-fill ~/pics/wallpapers/simon1.jpg # solarized
# feh --bg-fill ~/pics/wallpapers/1155989-rainbow-polygons.jpg  --bg-fill ~/pics/wallpapers/media_Ff_g2i3UYAAEL54.jpg --bg-fill ~/pics/wallpapers/media_FZC3t4FUsAAPfOg.jpg # anime girls
feh --bg-fill ~/pics/wallpapers/1155989-rainbow-polygons.jpg  --bg-fill ~/pics/wallpapers/a-solitary-drive-1920x1080-v0-rwitfbbmnpnb1.png --bg-fill ~/pics/wallpapers/yuan-zhang-1.jpg
bash ~/.config/polybar/launch.sh
# eww daemon &
# eww open bar0
~/.local/bin/picom-ibhagwan -b --experimental-backends
