[colors]
# The default text color
foreground = "#839496"
# The default background color
background = "#002b36"
# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#839496"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#002b36"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#268bd2"
# the foreground color of selected text
selection_fg = "#002b36"
# the background color of selected text
selection_bg = "#839496"

ansi = ["#073642", "#dc322f", "#859900", "#b58900", "#268bd2", "#d33682", "#2aa198", "#eee8d5"]
brights = ["#002b36", "#cb4b16", "#586e75", "#657b83", "#839496", "#6c71c4", "#93a1a1", "#fdf6e3"]
