return {
  -- "nvim-neorg/neorg",
  -- build = ":Neorg sync-parsers",
  -- -- tag = "*",
  -- dependencies = { "nvim-lua/plenary.nvim" },
  -- config = function()
  --   require("neorg").setup {
  --     load = {
  --       ["core.defaults"] = {},
  --       ["core.completion"] = {
  --         config = {
  --           engine = "nvim-cmp"
  --         },
  --       },
  --       ["core.concealer"] = {
  --         config = {
  --           icon_preset = "diamond",
  --         },
  --       },
  --       ["core.dirman"] = {
  --         config = {
  --           workspaces = {
  --             notes = "~/study/notes",
  --           },
  --           default_workspace = "notes",
  --           index = "001_index.norg"
  --         },
  --       },
  --     },
  --   }
  -- end,
}
