# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

[window]

# opacity = 0.9

padding.x = 10
# padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 11.5
normal.family = "CartographCF Nerd Font"
normal.style = "Regular"
bold.family = "CartographCF Nerd Font"
bold.style = "DemiBold"
italic.family = "CartographCF Nerd Font"
italic.style = "Italic"
bold_italic.family = "CartographCF Nerd Font"
bold_italic.style = "ExtraBold Italic"


[colors.primary]
background = "#001e27"
foreground = "#9cc2c3"

[colors.normal]
black = '#002831'    # Black (Host)
red = '#d11c24'    # red (syntax string)
green = '#6cbe6c'    # green (command)
yellow = '#a57706'    # yellow (command second)
blue = '#2176c7'    # blue (path)
magenta = '#c61c6f'    # magenta (syntax var)
cyan = '#259286'    # cyan (prompt)
white= '#eae3cb'    # white

[colors.bright]
black= '#006488'    # Bright Black
red = '#f5163b'    # bright red (command error)
green = '#51ef84'    # bright green (exec)
yellow= '#b27e28'    # bright yellow
blue = '#178ec8'    # bright blue (folder)
magenta= '#e24d8e'    # bright magenta
cyan= '#00b39e'    # bright cyan
white= '#fcf4dc'    # bright white

[colors.cursor]
text = "#002b36"
cursor = "#9cc2c3"

[[hints.enabled]]
binding = { key = "O", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
