# Default colors
[colors.primary]
background = '#242b2e'
foreground = '#e57474'

# Cursor colors
[colors.cursor]
text = '#242b2e'
cursor = '#e57474'

# Normal colors
[colors.normal]
black   = '#1f2426'
red     = '#e57474'
green   = '#e58c8c'
yellow  = '#e5a4a4'
blue    = '#e5bcbc'
magenta = '#e5cccc'
cyan    = '#e5dcdc'
white   = '#f0eaea'

# Bright colors
[colors.bright]
black   = '#3a4144'
red     = '#e57474'
green   = '#e58c8c'
yellow  = '#e5a4a4'
blue    = '#e5bcbc'
magenta = '#e5cccc'
cyan    = '#e5dcdc'
white   = '#ffffff'
