# Default colors
[colors.primary]
background = '#111111'
foreground = '#d3d3d3'

# Cursor colors
[colors.cursor]
text = '#111111'
cursor= '#dadada'

# Normal colors
[colors.normal]
black = '#382c2f'
red = '#48393a'
green = '#65534d'
yellow = '#79665a'
blue = '#836e5e'
magenta = '#8e7766'
cyan = '#917781'
white = '#9a846d'

# Bright colors
[colors.bright]
black = '#ac9377'
red = '#baa17e'
green = '#bca282'
yellow = '#c1a67e'
blue = '#cfb48e'
magenta = '#d1baa3'
cyan = '#dfc39b'
white = '#eed8c4'
