[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "solarized"
directory = "/lucius/.config/leftwm/themes/solarized"
version = "0.0.0"
leftwm_versions = "*"
current = true

[[repos.themes]]
name = "test"
directory = "/lucius/.config/leftwm/themes/test"
version = "0.0.0"
leftwm_versions = "*"
current = false
