export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.ghcup/bin:$PATH
export PATH=$HOME/.config/emacs/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export R2MOD_INSTALL_DIR="/games/SteamLibrary/steamapps/common/Risk of Rain 2"
export R2MOD_COMPAT_DIR="/games/SteamLibrary/steamapps/compatdata/632360"

ZSH_THEME="daivasmara"
zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"
plugins=(git fast-syntax-highlighting zsh-autosuggestions autojump)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#344146"

source $ZSH/oh-my-zsh.sh
unsetopt beep
alias ls="bash ~/elash.sh"
alias cat="bat"
alias v="nvim"
alias c="clear"
alias hi="loginctl hibernate"
alias sx="startx"
alias reboot="loginctl reboot"
alias poweroff="loginctl poweroff"
alias wget="aria2c"
alias kitsune="cd ~/repos/kitsune && source ~/repos/venv/bin/activate"
alias sus="loginctl suspend-then-hibernate"
alias xsc="xclip -sel clip"
alias sw="swapon --show"
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

export BAT_THEME="Solarized (dark)"
export FPATH="/hdd/docs/eza/completions/zsh:$FPATH"
export EDITOR=nvim
