#!/bin/sh

# Recompile
cd "$XMONAD_CONFIG_DIR" && stack-bin install || exit

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T "$(stack-bin exec -- which xmonad)" "$1"
