resolver: lts-19.33

packages:
  - . 

extra-deps:
  - github: xmonad/x11
    commit: 8a33c4ebe7d0a1be96073d8c019f1f3901bbf344						
  - github: xmonad/xmonad
    commit: 5ecdf7591d4f4bc3e44571326e66dfe895393a20						
  - github: xmonad/xmonad-contrib
    commit: 6fba80168df60d8a151515601f046a22cf9efbf5						
  - xmobar-0.44.2

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true
    with_mpd: true

arch: x86_64
