resolver: lts-19.23

packages:
  - . 

extra-deps:
  - github: xmonad/x11
    commit: d91b15fd8bfe78fe2865976bd357d70381fd85ab				
  - github: xmonad/xmonad
    commit: cf4d6f31b1751318309ddcc1c5fd8aa71a6a453a				
  - github: xmonad/xmonad-contrib
    commit: 6373dc41fa4dfb2a12c20e431976ceee6fd03837				
  - xmobar-0.44.2
  - dbus-1.2.22

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true
    with_dbus: true
    with_mpd: true

arch: x86_64
