resolver: lts-19.23

packages:
  - . 

extra-deps:
  - github: xmonad/x11
    commit: 8a33c4ebe7d0a1be96073d8c019f1f3901bbf344					
  - github: xmonad/xmonad
    commit: 57c3a131253720e542fb399b229b697614642b53					
  - github: xmonad/xmonad-contrib
    commit: 6117a867d984f97fb689eca986eff2989b2fe069					
  - xmobar-0.44.2

flags:
  xmobar:
    with_xpm: true
    with_threaded: true
    with_xft: true
    with_rtsopts: true
    with_mpd: true

arch: x86_64
