# Monochromatic Alacritty Theme
# Original dark theme with much brighter path colors

[colors.primary]
background = "#18181b"  # very dark gray, almost black
foreground = "#d4d4d8"  # muted light gray
dim_foreground = "#a1a1aa"  # dimmed light gray
bright_foreground = "#f4f4f5"  # near white

[colors.cursor]
text = "#18181b"  # dark background for cursor text
cursor = "#d4d4d8"  # light gray cursor

[colors.vi_mode_cursor]
text = "#18181b"
cursor = "#a1a1aa"

[colors.search.matches]
foreground = "#18181b"
background = "#a1a1aa"

[colors.search.focused_match]
foreground = "#18181b"
background = "#d4d4d8"

[colors.footer_bar]
foreground = "#d4d4d8"
background = "#27272a"

[colors.hints.start]
foreground = "#18181b"
background = "#a1a1aa"

[colors.hints.end]
foreground = "#18181b"
background = "#d4d4d8"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "#18181b"
background = "#52525b"

# Normal colors - much brighter path colors
[colors.normal]
black = "#09090b"     # deeper black
red = "#7f1d1d"       # dark muted red
green = "#a1a1aa"     # much brighter for paths/directories
yellow = "#d4d4d8"    # much brighter gray
blue = "#a1a1aa"      # much brighter for directories
magenta = "#71717a"   # brighter gray
cyan = "#d4d4d8"      # much brighter for files/paths
white = "#e4e4e7"     # very light gray

# Bright colors - very bright path colors
[colors.bright]
black = "#27272a"     # dark gray
red = "#991b1b"       # slightly brighter muted red
green = "#d4d4d8"     # very bright for paths
yellow = "#f4f4f5"    # very bright gray
blue = "#d4d4d8"      # very bright for directories
magenta = "#a1a1aa"   # brighter gray
cyan = "#f4f4f5"      # very bright for files/paths
white = "#f4f4f5"     # near white

# Dim colors - brighter dim colors for paths
[colors.dim]
black = "#09090b"
red = "#5c1414"       # even more muted red
green = "#71717a"     # brighter for paths
yellow = "#a1a1aa"    # brighter gray
blue = "#71717a"      # brighter for directories
magenta = "#52525b"   # brighter gray
cyan = "#a1a1aa"      # brighter for files/paths
white = "#a1a1aa"     # dimmed light gray
